import React from 'react';
export const CountryData = ()=>{console.log( {
"ae" : "United Arab",
"ar" : "Argentina",
"at" : "Austria",
"au" : "Australia",
"be" : "Belgium",
"bg" : "Bulgria",
"br" : "Brazil",
"ca" : "Canada",
"ch" : "Switzerland",
"cn" : "China",
"co" : "Colombia",
"cu" : "Cuba",
"cz" : "Czechia",
"de" : "Germany",
"eg" : "Egypt",
"fr" : "France",
"gb" : "United Kingdom of Great Britain and Northern Ireland",
"gr" : "Greece",
"hk" : "Hong Kong",
"hu" : "Hungary",
"id" : "Indonesia",
"ie" : "Ireland",
"il" : "Israel",
"in" : "India",
"it" : "Italy",
"jp" : "Japan",
"kr" : "Republic of Korea",
"lt" : "Lithuania",
"lv" : "Latvia",
"ma" : "Morocco",
"mx" : "Mexico",
"my" : "Malaysia",
"ng" : "Nigeria",
"nl" : "Netherlands",
"no" : "Norway",
"nz" : "New Zealand",
"ph" : "Philippines",
"pl" : "Poland",
"pt" : "Portugal",
"ro" : "Romania",
"rs" : "Serbia",
"ru" : "Russian Federation",
"sa" : "Saudi Arabia",
"se" : "Sweden",
"sg" : "Singapore",
"si" : "Slovenia",
"sk" : "Slovakia",
"th" : "Thailand",
"tr" : "Turkey",
"tw" : "Taiwan",
"ua" : "Ukraine",
"us" : "United States of America",
"ve" : "Venezuela",
"za" : "South Africa"
}
)
}